"""edit shape code

Revision ID: 6b252e280c2c
Revises: 
Create Date: 2025-04-11 07:46:55.904634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b252e280c2c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('timeframe', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charts_id'), 'charts', ['id'], unique=False)
    op.create_table('shapes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chart_id', sa.Integer(), nullable=True),
    sa.Column('shape_id', sa.String(), nullable=True),
    sa.Column('shape_type', sa.String(), nullable=True),
    sa.Column('shape_code', sa.Integer(), nullable=False),
    sa.Column('shape_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chart_id'], ['charts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shape_code')
    )
    op.create_index(op.f('ix_shapes_id'), 'shapes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shapes_id'), table_name='shapes')
    op.drop_table('shapes')
    op.drop_index(op.f('ix_charts_id'), table_name='charts')
    op.drop_table('charts')
    # ### end Alembic commands ###
