#
#####################################################################################################################################################
#####################################################################################################################################################
##################################################################################################################################################### Tips
#
# - Always activate your environment before installing or updating packages.

# - Regularly export your environment to keep a backup of your package configuration.
#
#####################################################################################################################################################
#####################################################################################################################################################
##################################################################################################################################################### Basic
#
# conda --version                                           (Check Conda Version)
#
# conda update conda                                        (Update Conda)
#
#####################################################################################################################################################
#####################################################################################################################################################
##################################################################################################################################################### Environment Management
#
# conda create --name your_env_name                         (Create a New Environment)
#
# conda create --name your_env_name python=3.9 numpy pandas (Create a New Environment with Specific Packages)
#
# conda activate your_env_name                              (Activate an Environment)
#
# conda deactivate                                          (Deactivate the Current Environment)
#
# conda env list                                            (List All Environments)
#
# conda env remove --name your_env_name                     (Remove an Environment)
#
#####################################################################################################################################################
#####################################################################################################################################################
##################################################################################################################################################### Package Management
#
# conda install package_name                                (Install a Package)
#
# conda install -c conda-forge package_name                 (Install a Package from a Specific Channel)
#
# conda update package_name                                 (Update a Package)
#
# conda update --all                                        (Update All Packages in the Current Environment)
#
# conda remove package_name                                 (Remove a Package)
#
# conda list                                                (List Installed Packages)
#
#####################################################################################################################################################
#####################################################################################################################################################
##################################################################################################################################################### Search for Packages
#
# conda search package_name                                 (Search for a Package)
#
#####################################################################################################################################################
#####################################################################################################################################################
##################################################################################################################################################### Miscellaneous Commands
#
# conda info package_name                                   (Show Information About a Package)
#
# conda clean --all                                         (Clean Up Unused Packages and Cache)
#
# conda install package_name --dry-run                      (Check for Package Conflicts)
#
#####################################################################################################################################################
#####################################################################################################################################################
##################################################################################################################################################### environment.yml
#
# conda env export > environment.yml                        (Export Current Environment to YAML File)
#
# conda env create --file environment.yml                   (Create or Update an Environment from a YAML File)
#
# conda env update --file environment.yml --prune           (Use --prune when updating from a YAML file to remove unused packages)
#
name: Project_Brainy_Charts
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - ipykernel
  - ipython
  - fastapi
  - numpy
  - pandas
  - pydantic
  - requests
  - SQLAlchemy
#
#####################################################################################################################################################
#####################################################################################################################################################
#####################################################################################################################################################
#
